# Generated by Django 4.0.4 on 2022-07-08 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('8x10', '8x10'), ('10x12', '10x12'), ('11x14', '11x14'), ('16x20', '16x20'), ('20x24', '20x24'), ('24x36', '24x36'), ('30x40', '30x40')], max_length=7)),
                ('subject', models.CharField(choices=[('Traditional landscapes', 'Traditional landscapes'), ('Local views', 'Local views'), ('Modern or semi-abstract landscapes', 'Modern or semi-abstract landscapes'), ('Abstracts', 'Abstracts'), ('Portraits', 'Portraits'), ('Figure studies', 'Figure studies'), ('Seascapes, harbour and beach scenes', 'Seascapes, harbour and beach scenes'), ('Wildlife', 'Wildlife'), ('Impressionistic landscapes', 'Impressionistic landscapes'), ('Surrealism', 'Surrealism')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
